[package]
name = "pytrace_core"
version = "0.2.0"
authors = ["Vanille-N <neven.villani@gmail.com>"]
edition = "2018"
include = ["src/**/*", "README.md"]

[dependencies]
rand = "0.7"
threadpool = "1.8.*"
