[package]
name = "pytrace"
version = "0.2.1"
authors = ["Vanille-N <neven.villani@gmail.com>"]
edition = "2018"

[lib]
name = "pytrace"
crate-type = ["cdylib"]

[dependencies]
libtrace = {path = "../libtrace"}
glob = "*"

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]
